# --- !Ups

CREATE TABLE CATEGORY (
    ID VARCHAR(255) PRIMARY KEY,
    NAME VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE SUBCATEGORY (
    ID VARCHAR(255) PRIMARY KEY,
    PARENT_ID VARCHAR(255) FOREIGN KEY REFERENCES CATEGORY(ID),
    NAME VARCHAR(255) UNIQUE NOT NULL
);

# --- !Downs

DROP TABLE CATEGORY;
DROP TABLE SUBCATEGORY;