# --- !Ups

CREATE TABLE "CATEGORY" (
    "ID" VARCHAR NOT NULL PRIMARY KEY,
    "NAME" VARCHAR NOT NULL UNIQUE
);

CREATE TABLE "SUBCATEGORY" (
    "ID" VARCHAR PRIMARY KEY,
    "PARENT_ID" VARCHAR NOT NULL,
    "NAME" VARCHAR NOT NULL UNIQUE,
    FOREIGN KEY("PARENT_ID") REFERENCES CATEGORY("ID")
);

# --- !Downs

DROP TABLE CATEGORY;
DROP TABLE SUBCATEGORY;