# --- !Ups

CREATE TABLE "PRODUCT" (
    "ID" VARCHAR NOT NULL PRIMARY KEY,
    "SUBCATEGORY_ID" VARCHAR NOT NULL,
    "TITLE" VARCHAR NOT NULL,
    "PRICE" DECIMAL(19,2) NOT NULL,
    "DESCRIPTION" TEXT,
    "DATE" DATE NOT NULL,
    "QUANTITY" INTEGER NOT NULL,
    FOREIGN KEY("SUBCATEGORY_ID") REFERENCES SUBCATEGORY("ID")
);

CREATE TABLE "PHOTO" (
    "ID" VARCHAR NOT NULL PRIMARY KEY,
    "PRODUCT_ID" VARCHAR NOT NULL,
    "PHOTO" BLOB NOT NULL,
    FOREIGN KEY("PRODUCT_ID") REFERENCES PRODUCT("ID")
);

CREATE TABLE "OPINION" (
    "ID" VARCHAR NOT NULL PRIMARY KEY,
    "PRODUCT_ID" VARCHAR NOT NULL,
    "OPINION" TEXT NOT NULL,
    "RATING" INTEGER NOT NULL,
    FOREIGN KEY("PRODUCT_ID") REFERENCES PRODUCT("ID"),
    CHECK ( "RATING" >= 1 AND "RATING" <= 5)
);

# --- !Downs

DROP TABLE "PRODUCT";
DROP TABLE "PHOTO";
DROP TABLE "OPINION";