# --- !Ups

CREATE TABLE "BASKET" (
    "ID" VARCHAR NOT NULL PRIMARY KEY,
    "USER_ID" VARCHAR,
    "IS_BOUGHT" INTEGER NOT NULL,
    CHECK ("IS_BOUGHT" == 0 OR "IS_BOUGHT" == 1)
);

CREATE TABLE "ORDERED_PRODUCT" (
    "ID" VARCHAR NOT NULL PRIMARY KEY,
    "BASKET_ID" VARCHAR NOT NULL,
    "PRODUCT_ID" VARCHAR NOT NULL,
    "QUANTITY" INTEGER NOT NULL,
    FOREIGN KEY("BASKET_ID") REFERENCES BASKET("ID"),
    FOREIGN KEY("PRODUCT_ID") REFERENCES PRODUCT("ID")
);

# --- !Downs

DROP TABLE "ORDERED_PRODUCT";
DROP TABLE "BASKET";