# --- !Ups

CREATE TABLE "ORDER" (
    "ID" VARCHAR NOT NULL PRIMARY KEY,
    "BASKET_ID" VARCHAR NOT NULL UNIQUE,
    "STATE" VARCHAR NOT NULL,
    FOREIGN KEY("BASKET_ID") REFERENCES BASKET("ID"),
    CHECK ("STATE" IN ('PAID', 'NOT_PAID', 'CANCELLED', 'DELIVERED'))
);

CREATE TABLE "SHIPPING_INFORMATION" (
    "ID" VARCHAR NOT NULL PRIMARY KEY,
    "ORDER_ID" VARCHAR NOT NULL UNIQUE,
    "FIRST_NAME" VARCHAR NOT NULL,
    "LAST_NAME" VARCHAR NOT NULL,
    "E_MAIL" VARCHAR NOT NULL,
    "STREET" VARCHAR NOT NULL,
    "HOUSE_NUMBER" VARCHAR NOT NULL,
    "CITY" VARCHAR NOT NULL,
    "ZIP_CODE" VARCHAR NOT NULL,
    FOREIGN KEY("ORDER_ID") REFERENCES "ORDER"("ID")
);

CREATE TABLE "PAYMENT" (
    "ID" VARCHAR NOT NULL PRIMARY KEY,
    "ORDER_ID" VARCHAR NOT NULL UNIQUE,
    "IS_DONE" INTEGER NOT NULL,
    FOREIGN KEY("ORDER_ID") REFERENCES "ORDER"("ID"),
    CHECK ("IS_DONE" == 0 OR "IS_DONE" == 1)
);

# --- !Downs

DROP TABLE "ORDER";
DROP TABLE "SHIPPING_INFORMATION";
DROP TABLE "PAYMENT";